### ISSUE TITLE
something problem in data_utils_LA.py 

### ISSUE THREAD

**Issue by mimao123** [eurecom-asp/rawnet2-antispoofing#3]
def _parse_line(self, line):
        tokens = line.strip().split(' ')
        if self.is_eval:
            return ASVFile(speaker_id=tokens[0],
                file_name=tokens[1],
                path=os.path.join(self.files_dir, tokens[1] + '.flac'),
                sys_id=self.sysid_dict[tokens[2]],
                key=int(tokens[3] == 'bonafide'))
        return ASVFile(speaker_id=tokens[0],
            file_name=tokens[1],
            path=os.path.join(self.files_dir, tokens[1] + '.flac'),
            sys_id=self.sysid_dict[tokens[2]],
            key=int(tokens[3] == 'bonafide')

>maybe sys_id=self.sysid_dict[tokens[3]]? and key=int(tokens[4] == 'bonafide'))?   because tokens[2] == '-'

**Comment by TakHemlata** [comment]
Hello,

Yes, I think you downloaded protocol from asvspoof website.

As you can check in database folder in git repo for that this code will work fine.

Yes for protocol downloaded from ASVspoof 2019 website you need to use following:

def _parse_line(self, line):
    tokens = line.strip().split(' ')
    if self.is_eval:
        return ASVFile(speaker_id=tokens[0],
            file_name=tokens[1],
            path=os.path.join(self.files_dir, tokens[1] + '.flac'),
            sys_id=self.sysid_dict[tokens[3]],
            key=int(tokens[4] == 'bonafide'))
    return ASVFile(speaker_id=tokens[0],
        file_name=tokens[1],
        path=os.path.join(self.files_dir, tokens[1] + '.flac'),
        sys_id=self.sysid_dict[tokens[3]],
        key=int(tokens[4] == 'bonafide')

I will change the database folder and in the code also.

Thanks
