### ISSUE TITLE
some problems about this paper result

### ISSUE THREAD

**Issue by ZigHello** [eurecom-asp/rawnet2-antispoofing#4]
Dear author:
 Thank you so much for such a great job，I recently reproduced your work on the ASVspoof2019 LA dataset, I used s1, s2, s3 pre-trained models and did not get the results in the article,the best result is from the s1 pre-trained model, eer: 20.62%, which is a big gap with the results in the article, did I miss something?
<img width="397" alt="image" src="https://user-images.githubusercontent.com/49471624/201504938-582b976c-753d-4953-a520-bb69d3ce50f4.png">

<img width="938" alt="image" src="https://user-images.githubusercontent.com/49471624/201504037-db907392-7aff-4ed0-9f56-5a9eb235e3e9.png">

**Comment by TakHemlata** [comment]
Hello ZigHello,

Thanks for your interest. I again checked with pre-trained model and I got similar result. I assume maybe you did some mistake in EER computation.  Make sure that your score file is matched with protocol file. Otherwise it will give wrong performance.

Thanks

**Comment by Bonlin0** [comment]
I encountered the same problem during the reproduction , I executed the commands given in the Readme file, used the pre-trained model S1 provided in the repo, and got exactly the same results as @ZigHello .  I used the EER computation code from ASVspoof 2019 official website, and I got the same result. I checked the score file, and it is matched with protocol file.
Please, check the model again? @TakHemlata

**Comment by TakHemlata** [comment]
Hi Bonlin0

Thanks for letting me know. The pre-trained model was by mistake wrong.
I suggest you check this update github repo "https://github.com/asvspoof-challenge/2021/tree/main/LA/Baseline-RawNet2"  and train from the start or check with pre-trained model. This one we used for the 2021 challenge but the pre-trained model is on 2019 LA training data only.

I hope that helps.
Thanks
